USE [tas2]
GO

/****** Object:  Table [tas].[Tran_Timesheet]    Script Date: 30/01/2026 21:52:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [tas].[Tran_Timesheet](
	[AutoID] [INT] NOT NULL,
	[EmpNo] [INT] NOT NULL,
	[DT] [DATETIME] NULL,
	[dtIN] [DATETIME] NULL,
	[dtOUT] [DATETIME] NULL,
	[ShiftPatCode] [CHAR](2) NULL,
	[ShiftCode] [CHAR](10) NULL,
	[Actual_ShiftCode] [CHAR](10) NULL,
	[ShiftAllowance] [BIT] NULL,
	[OTType] [CHAR](10) NULL,
	[OTStartTime] [DATETIME] NULL,
	[OTEndTime] [DATETIME] NULL,
	[NoPayHours] [INT] NULL,
	[BusinessUnit] [CHAR](12) NULL,
	[GradeCode] [CHAR](10) NULL,
	[AbsenceReasonCode] [CHAR](10) NULL,
	[LeaveType] [CHAR](10) NULL,
	[RemarkCode] [CHAR](10) NULL,
	[DIL_Entitlement] [CHAR](10) NULL,
	[AbsenceReasonColumn] [CHAR](10) NULL,
	[CorrectionCode] [CHAR](10) NULL,
	[Processed] [BIT] NULL,
	[OnCallOut] [BIT] NULL,
	[OnDuty] [BIT] NULL,
	[ShiftSpanDate] [DATETIME] NULL,
	[ShiftSpan] [BIT] NULL,
	[ProcessID] [INT] NULL,
	[LastUpdateUser] [CHAR](20) NULL,
	[LastUpdateTime] [DATETIME] NULL,
	[XXXXXXXXXXXX_100] [BIT] NULL,
	[JobCategoryCode] [CHAR](6) NULL,
	[isMuslim] [BIT] NULL,
	[isRamadan] [BIT] NULL,
	[IsPublicHoliday] [BIT] NULL,
	[IsDILdayWorker] [BIT] NULL,
	[XXXXXXXXXXXX_200] [BIT] NULL,
	[In1] [CHAR](4) NULL,
	[In2] [CHAR](4) NULL,
	[Out1] [CHAR](4) NULL,
	[Out2] [CHAR](4) NULL,
	[Sch_A2] [CHAR](4) NULL,
	[Sch_D1] [CHAR](4) NULL,
	[Is_InOut_in_Shaving] [BIT] NULL,
	[XXXXXXXXXXXX_300] [BIT] NULL,
	[dtA1] [DATETIME] NULL,
	[dtA2] [DATETIME] NULL,
	[dtD1] [DATETIME] NULL,
	[dtD2] [DATETIME] NULL,
	[XXXXXXXXXXXX_400] [BIT] NULL,
	[Shaved_IN] [DATETIME] NULL,
	[Shaved_OUT] [DATETIME] NULL,
	[XXXXXXXXXXXX_500] [BIT] NULL,
	[IsEmployee_OR_Contractor] [BIT] NULL,
	[IsResigned] [BIT] NULL,
	[IsSalStaff] [BIT] NULL,
	[IsDayWorker_OR_Shifter] [BIT] NULL,
	[IsDriver] [BIT] NULL,
	[IsLiasonOfficer] [BIT] NULL,
	[IsHedger] [BIT] NULL,
	[IsOnDutyRota] [BIT] NULL,
	[ContractorGroupCode] [CHAR](10) NULL,
	[XXXXXXXXXXXX_600] [BIT] NULL,
	[IsLastRow] [BIT] NULL,
	[Duration_SubID] [INT] NULL,
	[Duration_Shift] [INT] NULL,
	[Duration_MaternityLeave] [INT] NULL,
	[Duration_ROA] [INT] NULL,
	[Duration_Required] [INT] NULL,
	[Duration_Worked] [INT] NULL,
	[Duration_Worked_Cumulative] [INT] NULL,
	[XXXXXXXXXXXX_700] [BIT] NULL,
	[SwipeSource] [CHAR](1) NULL,
	[XXXXXXXXXXXX_800] [BIT] NULL,
	[Duration_ShiftAllowance_Evening] [INT] NULL,
	[Duration_ShiftAllowance_Night] [INT] NULL,
	[XXXXXXXXXXXX_900] [BIT] NULL,
	[ShiftSpan_XID] [INT] NULL,
	[ShiftSpan_HoursDay1] [INT] NULL,
	[ShiftSpan_HoursDay2] [INT] NULL,
	[ShiftSpan_AwardOT] [INT] NULL,
	[ShiftSpan_2ndDayFullOT] [INT] NULL,
	[XXXXXXXXXXXX_1000] [BIT] NULL,
	[NetMinutes] [INT] NULL,
	[Upload_ID] [INT] NULL,
	[MealVoucherEligibility] [VARCHAR](10) NULL
) ON [PRIMARY]
GO


