// <auto-generated />
using System;
using KenHRApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KenHRApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250719203747_RefactorEmployeeEntitySchema")]
    partial class RefactorEmployeeEntitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kenuser")
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KenHRApp.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The primary key of the Employee entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AlternateEmail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlternateMobileNo")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateOfConfirmation")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("The unique ID of the employee");

                    b.Property<byte?>("EmployeeStatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaritalStatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OfficeExtNo")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("OfficeLandlineNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReligionCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReportingManagerCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ResidenceLandlineNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Salutation")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("WorkPermitExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkPermitID")
                        .HasColumnType("varchar(30)");

                    b.HasKey("EmployeeId")
                        .HasName("PrimaryKey_EmpNo");

                    b.ToTable("Employee", "kenuser");
                });
#pragma warning restore 612, 618
        }
    }
}
